# Generated by Django 5.2 on 2025-07-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Linkedin',
            field=models.URLField(blank=True),
        ),
    ]
