# Generated by Django 5.2 on 2025-07-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Linkedin',
            new_name='linkedin',
        ),
    ]
