# Generated by Django 5.2 on 2025-05-06 14:17

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('PRN', models.IntegerField()),
                ('description', models.TextField()),
                ('site_type', models.CharField(choices=[('bank', 'Bank'), ('ditch', 'Ditch'), ('enclosure', 'Enclosure'), ('field_system', 'Field System'), ('industrial', 'Industrial'), ('industrial', 'Industrial'), ('mound', 'Mound'), ('pit', 'Pit'), ('settlement', 'Settlement'), ('trackway', 'Trackway'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=100)),
                ('period', models.CharField(choices=[('neolithic', 'Neolithic'), ('bronze_age', 'Bronze Age'), ('iron_age', 'Iron Age'), ('roman', 'Roman'), ('medieval', 'Medieval'), ('post_medieval', 'Post Medieval'), ('modern', 'Modern'), ('unknown', 'Unknown')], max_length=100)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('location', django.contrib.gis.db.models.fields.PointField(max_length=150, srid=4326)),
            ],
        ),
    ]
