# Generated by Django 5.2 on 2025-05-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='test_field',
        ),
    ]
