# Generated by Django 5.2 on 2025-05-14 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_latitude_record_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
