# Generated by Django 5.2 on 2025-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_record_location_record_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
