# Generated by Django 5.2 on 2025-06-05 14:34

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_monument_type_alter_record_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_recorded',
            field=models.DateField(default=records.models.today_date),
        ),
    ]
