# Generated by Django 5.2 on 2025-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='polygonCoordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
