# Generated by Django 5.2 on 2025-06-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_record_polygoncoordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='polygonCoordinates',
            new_name='polygonCoordinate',
        ),
    ]
