# Generated by Django 5.2 on 2025-06-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_record_recorded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='record',
            name='longitude',
        ),
    ]
