# Generated by Django 5.2 on 2025-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_record_latitude_remove_record_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='polygonCoordinate',
            field=models.JSONField(default=''),
        ),
    ]
