# Generated by Django 5.2 on 2025-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_record_polygoncoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='PRN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
