# Generated by Django 5.2 on 2025-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_record_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='polygonCoordinate',
            field=models.JSONField(default=dict),
        ),
    ]
