# Generated by Django 5.2 on 2025-09-28 12:22

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_record_polygoncoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='PRN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/', validators=[records.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='record',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/', validators=[records.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='record',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/', validators=[records.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='record',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/', validators=[records.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='record',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/', validators=[records.models.validate_file_size]),
        ),
    ]
