# Generated by Django 5.2 on 2025-09-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_record_prn_alter_record_picture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='polygonCoordinate',
            field=models.JSONField(default=list),
        ),
    ]
