# Generated by Django 5.2 on 2025-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_record_polygoncoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='polygonCoordinate',
            field=models.JSONField(default=list),
        ),
    ]
